book:
  chapters:
    - index.qmd
    - acknowledgements.qmd   
    - 0-abstract.qmd
    - 1-introduction.qmd
    - 2-methods.qmd
    - 3-results.qmd
    - 4-discussion.qmd
    - 5-conclusions.qmd
    - references.qmd
  appendices:
    - app1-resources.qmd
    - app2-tools.qmd

format:
  docx: default # uncomment this line to get a word docx file
  html:
    theme: cosmo
