project:
  type: book

book:
  title: "The title of my most excellent thesis"
  author: "Jane Doe"
  date: today
  date-format: "MMMM YYYY"
  chapters:
    - index.qmd
    - acknowledgements.qmd
    - 0-abstract.qmd
    - 1-introduction.qmd
    - 2-methods.qmd
    - 3-results.qmd
    - 4-discussion.qmd
    - 5-conclusions.qmd
    - references.qmd
  appendices:
    - app1-resources.qmd
    - app2-tools.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
    toc: false
    papersize: a4
    header-includes: |
      \usepackage{titling}
      \preauthor{\begin{center}
        \includegraphics[width=5in,height=4in]{figures/IMG_20210719_134928644.jpg}\\ % cover figure
      \postauthor{\end{center}}
      \predate{\begin{center}}
        Master of Science in Biology\\
        Biodiversity, Evolution and Ecology\\
        Department of Biology\\
        University of Bergen\\
        \thedate\\
        \includegraphics[width=1in,height=1in]{figures/UiB-emblem500px_gray.png}\\}
      \postdate{\end{center}}

editor: visual

